spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processos_db
    username: postgres
    password: sl2248
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
